### ISSUE TITLE
Customizable Chat Name Colors

### ISSUE THREAD

**Issue by dmccoystephenson** [seventhroot/elysium#658]
## Desired Solution
As a regular player, I should be able to change the color of my name when it appears in the chat. As an operator, I should be able to change the color of the name of any player when it appears in the chat. Changes to name colors should be immediate and persist upon a server restart.

A list of channels excluded from the profile color override should be configurable in the config.yml. In other words, operators should be capable of configuring some channels to not allow players to override the color of their name that appears in the chat.

## Subtasks
- [x] Database Modifications
       Some new tables will be required to store the color of profile names.
- [x] Database Migrations
       Migrations will be necessary to bring old databases up to speed with the new database tables and any other changes that might have been made.
- [x] Chat Listener Modifications
       Chat listener(s) must be modified to use stored color for profiles if set.
- [x] User Configuration
       Players should be able to configure their profile name color.
- [x] Operator Configuration
       Operators should be able to configure the profile colors of any player.
- [x] Test RPKit Upgrade
       Functionality should be verified when upgrading RPKit from an old version that did not include the database changes to the new version with the database changes.

## Acceptance Criteria
- [x] Database modified
- [x] Database migrations created
- [x] Colors used in chat listener(s)
- [x] Users can configure colors
- [x] Changes to chat name colors persist upon restarting the server
- [x] Operators can configure colors
- [x] RPKit doesn't break after upgrading

**Comment by dmccoystephenson** [comment]
The branch for this work item can be found here:
https://github.com/dmccoystephenson/my-RPKit/tree/setchatnamecolor

(updated 3/27/2024)

**Comment by dmccoystephenson** [comment]
I can verify that the migration for the new table works and that the 'chat_name_color' associated with a minecraft profile id can be inserted, updated & queried.

Next step is to actually use the 'chat_name_color' value when a message gets sent to a channel.

**Comment by dmccoystephenson** [comment]
Added "Changes to chat name colors persist upon restarting the server" to the acceptance criteria

**Comment by dmccoystephenson** [comment]
This may be considered a duplicate of #627

**Comment by dmccoystephenson** [comment]
Fully implemented by #663
